---
title: "Interactive Plots"
author: "Kristin Elgersma"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(scales)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

```


```{r data_read, include = FALSE}
#Read in the clean COVID-19 data set
covid <- read_csv("./data/covid_final.csv", show_col_types = FALSE)
instacart <- read_csv("./data/instacart.csv", show_col_types = FALSE)
df <- read_rds("./data/df.rds")
```

Column 
-----------------------------------------------------------------------

### Chart A

```{r echo = FALSE}
#create data frame with new cases and 7 day average by date
dat <- covid %>%
  group_by(date) %>%
  summarise(
    case = sum(new_cases),
    case7 = sum(new_cases_7day)
  )

#create plot
covid.gg <- dat %>%
  mutate(text_label = str_c("\nNew cases - ",  case, #adding text for the tooltip
                            "\n7-day case average - ", case7,
                            "\nDate - ", date)) %>%
  ggplot() +
  geom_col(aes(x = date, y = case, color = case, text = text_label)) + #for new cases per day
  scale_color_paletteer_c("grDevices::Lajolla") +
  theme_minimal() +
  theme(
    legend.position = "none", #the legend really would not work, so I took it out
    axis.title.x = element_text(vjust = -0.8), #position x axis title
    axis.title.y = element_text(vjust = 3)
  ) +
  geom_line(aes(x = date, y = case7)) + #add 7-day rolling average as a line
  scale_y_continuous(labels = label_number(suffix = " M", scale = 1e-6)) + #suffix to truncate y axis
  scale_x_date(
    date_labels = "%b %Y", #only show month and year
    date_breaks = "3 months" #add regular breaks
  ) +
  labs(
    x = "February 2020 - February 2022",
    y = "New cases per day",
    title = "Figure 2. Global rolling average of new COVID-19 cases per day."
  ) +
  annotate("text", ##manually add text to describe 7-day average line, since none of the legends worked well when added to ggplotly
    x = as.Date("2020-05-01"),
    y = 1000000,
    label = "Black line = 7-day average",
    size = 3,
    hjust = 0
  )

ggplotly(covid.gg, tooltip = "text") 
  

```

### Chart B

```{r echo = FALSE}
df2 <- df %>%
  pivot_longer(
    cols = c(sample_size_mean, sample_size_sd, data_value_mean, data_value_sd),
    names_to = "measure",
    values_to = "value"
  ) %>%
  mutate(
    measure = fct_recode(measure,
      "Sample size (mean)" = "sample_size_mean",
      "Sample size (SD)" = "sample_size_sd",
      "Proportion (mean)" = "data_value_mean",
      "Proportion (SD)" = "data_value_sd"
    ),
    measure = fct_relevel(measure, c(
      "Sample size (mean)", "Sample size (SD)",
      "Proportion (mean)", "Proportion (SD)"
    ))
  ) %>%
  droplevels()

df2 %>%
  group_by(measure) %>%
  do(p = plot_ly(.,
    x = ~year,
    y = ~value,
    color  = ~response,
    type   = "bar",
    colors = "viridis", alpha = 0.5
  ) %>%
  layout(
    title  = "Figure 3. Minnesota health in 2002, 2006, and 2010",
    xaxis  = list(title = "Year"),
    yaxis  = list(title = " "),
    xaxis = list(type = "category"),
    showlegend = FALSE
  )) %>%
  subplot(nrows = 2, shareX = TRUE, shareY = TRUE)
```

Column
-----------------------------------------------------------------------

### Chart C

```{r echo = FALSE, fig.height = 20}
#Create the data set for the ggplot
instacart2 <- instacart %>%
  group_by(aisle) %>%
  summarise(n = n_distinct((order_id))) %>%
  mutate(aisle = str_to_title(aisle)) %>%
  mutate(aisle = as.factor(aisle)) %>%
  mutate(aisle = (fct_reorder(aisle, n))) %>%
  mutate(n2 = n) %>% #when I used the "n" variable for both x and fill in the ggplot, I couldn't get the tooltip to work, so I created a separate n2 column to use with the fill aesthetic 
  rename(Aisle = aisle, 
         Orders = n)

# Visualization
insta.gg <-instacart2 %>%
  ggplot(aes(x = Orders, y = Aisle, fill = n2)) +
  geom_col() +
  scale_fill_gradientn( # choose custom colors and cut points for color scale
    name = "Number of orders",
    colors = c("gray", "skyblue4", "goldenrod", "orchid"),
    values = scales::rescale(c(0, 2000, 2001, 7000, 7001, 11000, 11001, max(instacart2$n2)))
  ) +
  labs(
    title = "Figure 2. Number of Instacart orders per aisle",
    x = "Number of orders",
    y = "Aisle"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

ggplotly(insta.gg, tooltip = c("Aisle", "Orders")) #I couldn't get the text label thing to leave out the fill aesthetic, so I just chose which variables I wanted to include here 

```

